// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/vcc/on.proto

package org.exnebula.protobuf.vcc;

public final class ObjectNotation {
  private ObjectNotation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.exnebula.protobuf.vcc.ObjectNotation.objectDatum);
    registry.add(org.exnebula.protobuf.vcc.ObjectNotation.intDatum);
    registry.add(org.exnebula.protobuf.vcc.ObjectNotation.stringDatum);
    registry.add(org.exnebula.protobuf.vcc.ObjectNotation.objectData);
  }
  public interface DatumOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Datum> {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class Datum extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Datum> implements DatumOrBuilder {
    // Use Datum.newBuilder() to construct.
    private Datum(Builder builder) {
      super(builder);
    }
    private Datum(boolean noInit) {}
    
    private static final Datum defaultInstance;
    public static Datum getDefaultInstance() {
      return defaultInstance;
    }
    
    public Datum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_Datum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_Datum_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<org.exnebula.protobuf.vcc.ObjectNotation.Datum>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      extensionWriter.writeUntil(1001, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.Datum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.exnebula.protobuf.vcc.ObjectNotation.Datum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          org.exnebula.protobuf.vcc.ObjectNotation.Datum, Builder> implements org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_Datum_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_Datum_fieldAccessorTable;
      }
      
      // Construct using org.exnebula.protobuf.vcc.ObjectNotation.Datum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.Datum.getDescriptor();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum getDefaultInstanceForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.Datum.getDefaultInstance();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum build() {
        org.exnebula.protobuf.vcc.ObjectNotation.Datum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.exnebula.protobuf.vcc.ObjectNotation.Datum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.exnebula.protobuf.vcc.ObjectNotation.Datum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum buildPartial() {
        org.exnebula.protobuf.vcc.ObjectNotation.Datum result = new org.exnebula.protobuf.vcc.ObjectNotation.Datum(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.exnebula.protobuf.vcc.ObjectNotation.Datum) {
          return mergeFrom((org.exnebula.protobuf.vcc.ObjectNotation.Datum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.exnebula.protobuf.vcc.ObjectNotation.Datum other) {
        if (other == org.exnebula.protobuf.vcc.ObjectNotation.Datum.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:vcc.Datum)
    }
    
    static {
      defaultInstance = new Datum(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vcc.Datum)
  }
  
  public interface IntDatumOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 value = 1;
    boolean hasValue();
    int getValue();
  }
  public static final class IntDatum extends
      com.google.protobuf.GeneratedMessage
      implements IntDatumOrBuilder {
    // Use IntDatum.newBuilder() to construct.
    private IntDatum(Builder builder) {
      super(builder);
    }
    private IntDatum(boolean noInit) {}
    
    private static final IntDatum defaultInstance;
    public static IntDatum getDefaultInstance() {
      return defaultInstance;
    }
    
    public IntDatum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_IntDatum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_IntDatum_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getValue() {
      return value_;
    }
    
    private void initFields() {
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.IntDatum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.exnebula.protobuf.vcc.ObjectNotation.IntDatum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.exnebula.protobuf.vcc.ObjectNotation.IntDatumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_IntDatum_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_IntDatum_fieldAccessorTable;
      }
      
      // Construct using org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.getDescriptor();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.IntDatum getDefaultInstanceForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.getDefaultInstance();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.IntDatum build() {
        org.exnebula.protobuf.vcc.ObjectNotation.IntDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.exnebula.protobuf.vcc.ObjectNotation.IntDatum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.exnebula.protobuf.vcc.ObjectNotation.IntDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.IntDatum buildPartial() {
        org.exnebula.protobuf.vcc.ObjectNotation.IntDatum result = new org.exnebula.protobuf.vcc.ObjectNotation.IntDatum(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.exnebula.protobuf.vcc.ObjectNotation.IntDatum) {
          return mergeFrom((org.exnebula.protobuf.vcc.ObjectNotation.IntDatum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.exnebula.protobuf.vcc.ObjectNotation.IntDatum other) {
        if (other == org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 value = 1;
      private int value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getValue() {
        return value_;
      }
      public Builder setValue(int value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vcc.IntDatum)
    }
    
    static {
      defaultInstance = new IntDatum(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vcc.IntDatum)
  }
  
  public interface StringDatumOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string value = 1;
    boolean hasValue();
    String getValue();
  }
  public static final class StringDatum extends
      com.google.protobuf.GeneratedMessage
      implements StringDatumOrBuilder {
    // Use StringDatum.newBuilder() to construct.
    private StringDatum(Builder builder) {
      super(builder);
    }
    private StringDatum(boolean noInit) {}
    
    private static final StringDatum defaultInstance;
    public static StringDatum getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringDatum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_StringDatum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_StringDatum_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.StringDatum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.exnebula.protobuf.vcc.ObjectNotation.StringDatum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.exnebula.protobuf.vcc.ObjectNotation.StringDatumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_StringDatum_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_StringDatum_fieldAccessorTable;
      }
      
      // Construct using org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.getDescriptor();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.StringDatum getDefaultInstanceForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.getDefaultInstance();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.StringDatum build() {
        org.exnebula.protobuf.vcc.ObjectNotation.StringDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.exnebula.protobuf.vcc.ObjectNotation.StringDatum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.exnebula.protobuf.vcc.ObjectNotation.StringDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.StringDatum buildPartial() {
        org.exnebula.protobuf.vcc.ObjectNotation.StringDatum result = new org.exnebula.protobuf.vcc.ObjectNotation.StringDatum(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.exnebula.protobuf.vcc.ObjectNotation.StringDatum) {
          return mergeFrom((org.exnebula.protobuf.vcc.ObjectNotation.StringDatum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.exnebula.protobuf.vcc.ObjectNotation.StringDatum other) {
        if (other == org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string value = 1;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:vcc.StringDatum)
    }
    
    static {
      defaultInstance = new StringDatum(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vcc.StringDatum)
  }
  
  public interface ObjectDatumOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .vcc.ObjectNode value = 1;
    boolean hasValue();
    org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode getValue();
    org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder getValueOrBuilder();
  }
  public static final class ObjectDatum extends
      com.google.protobuf.GeneratedMessage
      implements ObjectDatumOrBuilder {
    // Use ObjectDatum.newBuilder() to construct.
    private ObjectDatum(Builder builder) {
      super(builder);
    }
    private ObjectDatum(boolean noInit) {}
    
    private static final ObjectDatum defaultInstance;
    public static ObjectDatum getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObjectDatum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectDatum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectDatum_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .vcc.ObjectNode value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode getValue() {
      return value_;
    }
    public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder getValueOrBuilder() {
      return value_;
    }
    
    private void initFields() {
      value_ = org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getValue().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectDatum_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectDatum_fieldAccessorTable;
      }
      
      // Construct using org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (valueBuilder_ == null) {
          value_ = org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance();
        } else {
          valueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.getDescriptor();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum getDefaultInstanceForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.getDefaultInstance();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum build() {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum buildPartial() {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum result = new org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum) {
          return mergeFrom((org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum other) {
        if (other == org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.getDefaultInstance()) return this;
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        if (!getValue().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder subBuilder = org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.newBuilder();
              if (hasValue()) {
                subBuilder.mergeFrom(getValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .vcc.ObjectNode value = 1;
      private org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode value_ = org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder> valueBuilder_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode getValue() {
        if (valueBuilder_ == null) {
          return value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      public Builder setValue(org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setValue(
          org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeValue(org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode value) {
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              value_ != org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance()) {
            value_ =
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance();
          onChanged();
        } else {
          valueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder getValueBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder, org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder>(
                  value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:vcc.ObjectDatum)
    }
    
    static {
      defaultInstance = new ObjectDatum(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vcc.ObjectDatum)
  }
  
  public interface ObjectNodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string buildClass = 1;
    boolean hasBuildClass();
    String getBuildClass();
    
    // required int32 version = 2;
    boolean hasVersion();
    int getVersion();
    
    // repeated .vcc.Datum data = 3;
    java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum> 
        getDataList();
    org.exnebula.protobuf.vcc.ObjectNotation.Datum getData(int index);
    int getDataCount();
    java.util.List<? extends org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder> 
        getDataOrBuilderList();
    org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder getDataOrBuilder(
        int index);
  }
  public static final class ObjectNode extends
      com.google.protobuf.GeneratedMessage
      implements ObjectNodeOrBuilder {
    // Use ObjectNode.newBuilder() to construct.
    private ObjectNode(Builder builder) {
      super(builder);
    }
    private ObjectNode(boolean noInit) {}
    
    private static final ObjectNode defaultInstance;
    public static ObjectNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObjectNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectNode_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string buildClass = 1;
    public static final int BUILDCLASS_FIELD_NUMBER = 1;
    private java.lang.Object buildClass_;
    public boolean hasBuildClass() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getBuildClass() {
      java.lang.Object ref = buildClass_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          buildClass_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBuildClassBytes() {
      java.lang.Object ref = buildClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        buildClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 version = 2;
    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getVersion() {
      return version_;
    }
    
    // repeated .vcc.Datum data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum> data_;
    public java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum> getDataList() {
      return data_;
    }
    public java.util.List<? extends org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    public int getDataCount() {
      return data_.size();
    }
    public org.exnebula.protobuf.vcc.ObjectNotation.Datum getData(int index) {
      return data_.get(index);
    }
    public org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    
    private void initFields() {
      buildClass_ = "";
      version_ = 0;
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBuildClass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBuildClassBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, version_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(3, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBuildClassBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.exnebula.protobuf.vcc.ObjectNotation.ObjectNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectNode_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.exnebula.protobuf.vcc.ObjectNotation.internal_static_vcc_ObjectNode_fieldAccessorTable;
      }
      
      // Construct using org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        buildClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDescriptor();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode getDefaultInstanceForType() {
        return org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance();
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode build() {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode buildPartial() {
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode result = new org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.buildClass_ = buildClass_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode) {
          return mergeFrom((org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode other) {
        if (other == org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.getDefaultInstance()) return this;
        if (other.hasBuildClass()) {
          setBuildClass(other.getBuildClass());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000004);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBuildClass()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              buildClass_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
            case 26: {
              org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder subBuilder = org.exnebula.protobuf.vcc.ObjectNotation.Datum.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string buildClass = 1;
      private java.lang.Object buildClass_ = "";
      public boolean hasBuildClass() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getBuildClass() {
        java.lang.Object ref = buildClass_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          buildClass_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBuildClass(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        buildClass_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuildClass() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buildClass_ = getDefaultInstance().getBuildClass();
        onChanged();
        return this;
      }
      void setBuildClass(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        buildClass_ = value;
        onChanged();
      }
      
      // required int32 version = 2;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .vcc.Datum data = 3;
      private java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = new java.util.ArrayList<org.exnebula.protobuf.vcc.ObjectNotation.Datum>(data_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.exnebula.protobuf.vcc.ObjectNotation.Datum, org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder, org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder> dataBuilder_;
      
      public java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      public Builder setData(
          int index, org.exnebula.protobuf.vcc.ObjectNotation.Datum value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setData(
          int index, org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addData(org.exnebula.protobuf.vcc.ObjectNotation.Datum value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addData(
          int index, org.exnebula.protobuf.vcc.ObjectNotation.Datum value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addData(
          org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addData(
          int index, org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends org.exnebula.protobuf.vcc.ObjectNotation.Datum> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            org.exnebula.protobuf.vcc.ObjectNotation.Datum.getDefaultInstance());
      }
      public org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, org.exnebula.protobuf.vcc.ObjectNotation.Datum.getDefaultInstance());
      }
      public java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.exnebula.protobuf.vcc.ObjectNotation.Datum, org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder, org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.exnebula.protobuf.vcc.ObjectNotation.Datum, org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder, org.exnebula.protobuf.vcc.ObjectNotation.DatumOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:vcc.ObjectNode)
    }
    
    static {
      defaultInstance = new ObjectNode(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vcc.ObjectNode)
  }
  
  public static final int OBJECTDATUM_FIELD_NUMBER = 10;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.exnebula.protobuf.vcc.ObjectNotation.Datum,
      org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum> objectDatum = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.class,
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.getDefaultInstance());
  public static final int INTDATUM_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.exnebula.protobuf.vcc.ObjectNotation.Datum,
      org.exnebula.protobuf.vcc.ObjectNotation.IntDatum> intDatum = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.class,
        org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.getDefaultInstance());
  public static final int STRINGDATUM_FIELD_NUMBER = 12;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.exnebula.protobuf.vcc.ObjectNotation.Datum,
      org.exnebula.protobuf.vcc.ObjectNotation.StringDatum> stringDatum = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.class,
        org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.getDefaultInstance());
  public static final int OBJECTDATA_FIELD_NUMBER = 30;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.exnebula.protobuf.vcc.ObjectNotation.Datum,
      java.util.List<org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum>> objectData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.class,
        org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vcc_Datum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcc_Datum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vcc_IntDatum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcc_IntDatum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vcc_StringDatum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcc_StringDatum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vcc_ObjectDatum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcc_ObjectDatum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vcc_ObjectNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcc_ObjectNode_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/protobuf/vcc/on.proto\022\003vcc\"\034\n" +
      "\005Datum\022\014\n\004name\030\001 \002(\t*\005\010\n\020\351\007\"\031\n\010IntDatum\022" +
      "\r\n\005value\030\001 \002(\005\"\034\n\013StringDatum\022\r\n\005value\030\001" +
      " \002(\t\"-\n\013ObjectDatum\022\036\n\005value\030\001 \002(\0132\017.vcc" +
      ".ObjectNode\"K\n\nObjectNode\022\022\n\nbuildClass\030" +
      "\001 \002(\t\022\017\n\007version\030\002 \002(\005\022\030\n\004data\030\003 \003(\0132\n.v" +
      "cc.Datum:1\n\013objectDatum\022\n.vcc.Datum\030\n \001(" +
      "\0132\020.vcc.ObjectDatum:+\n\010intDatum\022\n.vcc.Da" +
      "tum\030\013 \001(\0132\r.vcc.IntDatum:1\n\013stringDatum\022" +
      "\n.vcc.Datum\030\014 \001(\0132\020.vcc.StringDatum:0\n\no",
      "bjectData\022\n.vcc.Datum\030\036 \003(\0132\020.vcc.Object" +
      "DatumB+\n\031org.exnebula.protobuf.vccB\016Obje" +
      "ctNotation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_vcc_Datum_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_vcc_Datum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vcc_Datum_descriptor,
              new java.lang.String[] { "Name", },
              org.exnebula.protobuf.vcc.ObjectNotation.Datum.class,
              org.exnebula.protobuf.vcc.ObjectNotation.Datum.Builder.class);
          internal_static_vcc_IntDatum_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_vcc_IntDatum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vcc_IntDatum_descriptor,
              new java.lang.String[] { "Value", },
              org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.class,
              org.exnebula.protobuf.vcc.ObjectNotation.IntDatum.Builder.class);
          internal_static_vcc_StringDatum_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_vcc_StringDatum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vcc_StringDatum_descriptor,
              new java.lang.String[] { "Value", },
              org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.class,
              org.exnebula.protobuf.vcc.ObjectNotation.StringDatum.Builder.class);
          internal_static_vcc_ObjectDatum_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_vcc_ObjectDatum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vcc_ObjectDatum_descriptor,
              new java.lang.String[] { "Value", },
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.class,
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectDatum.Builder.class);
          internal_static_vcc_ObjectNode_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_vcc_ObjectNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vcc_ObjectNode_descriptor,
              new java.lang.String[] { "BuildClass", "Version", "Data", },
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.class,
              org.exnebula.protobuf.vcc.ObjectNotation.ObjectNode.Builder.class);
          objectDatum.internalInit(descriptor.getExtensions().get(0));
          intDatum.internalInit(descriptor.getExtensions().get(1));
          stringDatum.internalInit(descriptor.getExtensions().get(2));
          objectData.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
